### ISSUE TITLE
DNS lookup for api.openstreetmap.org failed

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1015]
```
java.net.UnknownHostException: Unable to resolve host "api.openstreetmap.org": No address associated with hostname
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
at java.net.InetAddress.getAllByName(InetAddress.java:1154)
at okhttp3.m$1.a(Dns.java:40)
at okhttp3.internal.connection.e.a(RouteSelector.java:185)
at okhttp3.internal.connection.e.b(RouteSelector.java:3149)
at okhttp3.internal.connection.f.a(StreamAllocation.java:214)
at okhttp3.internal.connection.f.a(StreamAllocation.java:135)
at okhttp3.internal.connection.f.a(StreamAllocation.java:114)
at okhttp3.internal.connection.a.a(ConnectInterceptor.java:42)
at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
at okhttp3.internal.a.a.a(CacheInterceptor.java:93)
at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
at okhttp3.internal.b.a.a(BridgeInterceptor.java:93)
at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
at okhttp3.internal.b.j.a(RetryAndFollowUpInterceptor.java:126)
at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
at se.akerfeldt.okhttp.signpost.c.a(SigningInterceptor.java:46)
at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
at okhttp3.v.b(RealCall.java:250)
at okhttp3.v.a(RealCall.java:93)
at de.blau.android.osm.Server.a(Server.java:879)
at de.blau.android.osm.StorageDelegator.a(StorageDelegator.java:50245)
at de.blau.android.Logic$6.a(Logic.java:3668)
at de.blau.android.Logic$6.doInBackground(Logic.java:3650)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
at libcore.io.Linux.android_getaddrinfo(Native Method)
at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
... 34 more
```

@HolgerJeromin this is from the crash dump you submitted a couple of hours back. Essentially the DNS lookup of the API domain failed, anything else to report from your side?

**Comment by HolgerJeromin** [comment]
Thanks.
I am on an unstable wifi. Occurs often while uploading. 
Submitting more dumps does not work without wifi :-)

**Comment by HolgerJeromin** [comment]
So I have Wifi, select upload, then the connection drops and vespucci informs me about the problem.

**Comment by simonpoole** [comment]
@HolgerJeromin are you still having the issue? There were a couple of reports of similar issues with JOSM over the last couple of days, so it could simply be some kind of general DNS issue.

**Comment by HolgerJeromin** [comment]
You are right. Same unstable wifi, but solid vespucci behavoir. Or my new place at the pool has better wifi. :-D 

Free to close this issue.

**Comment by HolgerJeromin** [comment]
Or an dns issue could be catched nicer...

**Comment by simonpoole** [comment]
> 
> 
> Or an dns issue could be catched nicer...

The problem is that actually re-creating that specific error is difficult, so I have no idea what the actual behaviour looks like.
