### ISSUE TITLE
NPE parsing coordinates

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1087]
Entering 1°N,1°E will crash the coordinate parsing.
```
01-28 19:25:42.514: E/ACRA(16545): ACRA caught a NullPointerException for de.blau.android
01-28 19:25:42.514: E/ACRA(16545): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
01-28 19:25:42.514: E/ACRA(16545): 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
01-28 19:25:42.514: E/ACRA(16545): 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
01-28 19:25:42.514: E/ACRA(16545): 	at java.lang.Double.parseDouble(Double.java:539)
01-28 19:25:42.514: E/ACRA(16545): 	at de.blau.android.util.CoordinateParser.coordFromMatcher(CoordinateParser.java:352)
01-28 19:25:42.514: E/ACRA(16545): 	at de.blau.android.util.CoordinateParser.parseVerbatimCoordinates(CoordinateParser.java:180)
01-28 19:25:42.514: E/ACRA(16545): 	at de.blau.android.geocode.CoordinatesOrOLC$1.processLine(CoordinatesOrOLC.java:81)
01-28 19:25:42.514: E/ACRA(16545): 	at de.blau.android.dialogs.TextLineDialog$2$1.onClick(TextLineDialog.java:133)
```

**Comment by simonpoole** [comment]
Comment from mstock 

> wenn eine Capture-Group in einer Non-Capturing-Group ist, der ein ? folgt (letztes ? auf Zeile 35), dann ist die ja optional, und wenn der Teil im String einfach fehlt, dann kommt wohl null raus

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/1e1e831bb227568c0976f43cb86f810ddcac1cf2
