### ISSUE TITLE
Crash when opening tag editor on landuse (and other) objects

### ISSUE THREAD

**Issue by johantiden** [MarcusWolschon/osmeditor4android#1211]
## Vespucci Version
15.0.0.6

## Download source
github code f4164c9d1

## Device (Manufacturer and Model)
Pixel 3 XL crosshatch

## Android Version 
Android 10, LineageOS 

## Behaviour/Symptoms
Selecting an area with certain tags and then opening the tags editor results in a crash.

## Expected Behaviour
No crash :)

## How to recreate
1. Select an area with landuse=grass. I used https://www.openstreetmap.org/way/755861509
2. Click the "Properties" button to open the tag editor.

Crash

## Crash dump submitted (no or yes + date)
Yes, 2020-08-07. Message is 755861509. 
There are a bunch of other reports over a few weeks back.

**Comment by johantiden** [comment]
Log output:
```
2020-08-07 23:46:27.988 7603-7603/? D/TagEditorFragment: is visible
2020-08-07 23:46:27.989 7603-7603/? D/TagEditorFragment: onFocusChange key
2020-08-07 23:46:27.989 7603-7603/? D/TagEditorFragment: setting new autocompletePresetItem
2020-08-07 23:46:27.989 7603-7603/? E/de.blau.android.presets.Preset: Linked presets for Grass
2020-08-07 23:46:27.989 7603-7603/? D/de.blau.android.presets.Preset: getItemIndexByName No name
2020-08-07 23:46:27.991 7603-7603/? D/de.blau.android.presets.Preset: getItemIndexByName Payment Methods
2020-08-07 23:46:27.991 7603-7603/? D/de.blau.android.presets.Preset: getItemIndexByName Contact
2020-08-07 23:46:27.992 7603-7603/? D/de.blau.android.presets.Preset: getItemIndexByName Contact ('contact:*')
2020-08-07 23:46:27.992 7603-7603/? D/de.blau.android.presets.Preset: getItemIndexByName Address
2020-08-07 23:46:27.992 7603-7603/? D/de.blau.android.presets.Preset: getItemIndexByName Building
2020-08-07 23:46:27.993 7603-7603/? D/AndroidRuntime: Shutting down VM
2020-08-07 23:46:27.994 7603-7603/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.blau.android, PID: 7603
    java.lang.NullPointerException: Attempt to invoke virtual method 'void de.blau.android.presets.Preset.addToRootGroup(de.blau.android.presets.Preset[])' on a null object reference
        at de.blau.android.propertyeditor.PresetFragment.update(PresetFragment.java:341)
        at de.blau.android.propertyeditor.PropertyEditor.update(PropertyEditor.java:1263)
        at de.blau.android.propertyeditor.TagEditorFragment.updateAutocompletePresetItem(TagEditorFragment.java:612)
        at de.blau.android.propertyeditor.TagEditorFragment.getKeyAutocompleteAdapter(TagEditorFragment.java:849)
        at de.blau.android.propertyeditor.TagEditorFragment.access$500(TagEditorFragment.java:88)
        at de.blau.android.propertyeditor.TagEditorFragment$1.onFocusChange(TagEditorFragment.java:1087)
        at android.view.View.onFocusChanged(View.java:7927)
        at android.widget.TextView.onFocusChanged(TextView.java:10811)
        at android.widget.AutoCompleteTextView.onFocusChanged(AutoCompleteTextView.java:1172)
        at android.view.View.handleFocusGainInternal(View.java:7597)
        at android.view.View.requestFocusNoSearch(View.java:12962)
        at android.view.View.requestFocus(View.java:12936)
        at android.view.View.requestFocus(View.java:12903)
        at android.view.View.requestFocus(View.java:12845)
        at de.blau.android.propertyeditor.TagEditorFragment.onCreateView(TagEditorFragment.java:328)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:235)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25086)
2020-08-07 23:46:27.994 7603-7603/? E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3083)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1857)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2146)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-08-07 23:46:27.996 7603-7603/? E/ACRA: ACRA caught a NullPointerException for de.blau.android
    java.lang.NullPointerException: Attempt to invoke virtual method 'void de.blau.android.presets.Preset.addToRootGroup(de.blau.android.presets.Preset[])' on a null object reference
        at de.blau.android.propertyeditor.PresetFragment.update(PresetFragment.java:341)
        at de.blau.android.propertyeditor.PropertyEditor.update(PropertyEditor.java:1263)
        at de.blau.android.propertyeditor.TagEditorFragment.updateAutocompletePresetItem(TagEditorFragment.java:612)
        at de.blau.android.propertyeditor.TagEditorFragment.getKeyAutocompleteAdapter(TagEditorFragment.java:849)
        at de.blau.android.propertyeditor.TagEditorFragment.access$500(TagEditorFragment.java:88)
        at de.blau.android.propertyeditor.TagEditorFragment$1.onFocusChange(TagEditorFragment.java:1087)
        at android.view.View.onFocusChanged(View.java:7927)
        at android.widget.TextView.onFocusChanged(TextView.java:10811)
        at android.widget.AutoCompleteTextView.onFocusChanged(AutoCompleteTextView.java:1172)
        at android.view.View.handleFocusGainInternal(View.java:7597)
        at android.view.View.requestFocusNoSearch(View.java:12962)
        at android.view.View.requestFocus(View.java:12936)
        at android.view.View.requestFocus(View.java:12903)
        at android.view.View.requestFocus(View.java:12845)
        at de.blau.android.propertyeditor.TagEditorFragment.onCreateView(TagEditorFragment.java:328)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:235)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
2020-08-07 23:46:27.996 7603-7603/? E/ACRA:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
        at android.view.View.measure(View.java:25086)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3083)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1857)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2146)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-08-07 23:46:28.020 674-674/? E/SELinux: avc:  denied  { find } for service=meminfo pid=7732 uid=10296 scontext=u:r:untrusted_app:s0:c40,c257,c512,c768 tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
2020-08-07 23:46:28.041 7603-7616/? I/de.blau.androi: Background concurrent copying GC freed 465815(16MB) AllocSpace objects, 18(424KB) LOS objects, 66% free, 24MB/72MB, paused 34us total 142.713ms
2020-08-07 23:46:28.048 7603-7618/? W/System: A resource failed to call end. 
2020-08-07 23:46:28.099 1384-3086/? I/ActivityTaskManager: START u0 {flg=0x10000000 cmp=de.blau.android/org.acra.dialog.CrashReportDialog (has extras)} from uid 10296
2020-08-07 23:46:28.104 940-940/? D/android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 1
2020-08-07 23:46:28.108 7603-7603/? I/Process: Sending signal. PID: 7603 SIG: 9
```

**Comment by simonpoole** [comment]
I saw the crashes. They would indicate that there is something wrong with your preset configuration (it naturally should not crash anyway), do you have any additional presets configured?

**Comment by johantiden** [comment]
Nope, just the "Built-in preset".

**Comment by johantiden** [comment]
Perhaps a problem caused by building the app myself?

**Comment by johantiden** [comment]
Hmm I just switched render style to "Default" instead of "Color Round Nodes" and the crash stopped!

**Comment by simonpoole** [comment]
I suppose you might have a corrupted preset file. I don't see how the program itself could show that behaviour from a local build.

**Comment by simonpoole** [comment]
> Hmm I just switched render style to "Default" instead of "Color Round Nodes" and the crash stopped!
> 
> Everything seems fine now! That was unexpected... 

They should be the same though, I'll give it a look tomorrow.

**Comment by johantiden** [comment]
That sounds right. I prefer the uniformity of the grid view.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/5d607b1ddf1f6997e0d65da1b58b05752acaacd8

The was specific to 15.0 as the androidx libraries seem to behave slightly different as to when the  create the Fragments in the PropertyEditor layout than the older libs. We've seen a similar issue before. 

The reason that this was slightly object specific was simply that the crash only happened if the autocomplete adapter for the object with focus was being built and set or not.

**Comment by johantiden** [comment]
Nice work! Race conditions are always a pita.

**Comment by johantiden** [comment]
I will test that version tonight!

**Comment by johantiden** [comment]
That tag has a lower number than before. Mistake?

**Comment by johantiden** [comment]
BTW @simonpoole there are still a few `Util.beep()` remaining! I accidentally run the long press in simple mode very often. Annoys the hell out of my wife :)

**Comment by simonpoole** [comment]
Nope, the fourth number indicates beta builds  0 release.

Am 8. August 2020 20:33:09 MESZ schrieb "Johan Tidén" <notifications@github.com>:
>That tag has a lower number than before. Mistake?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarcusWolschon/osmeditor4android/issues/1211#issuecomment-670959788

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit Kaiten Mail gesendet.

**Comment by johantiden** [comment]
I can't reproduce the crash with the new version :+1: :1st_place_medal:
