### ISSUE TITLE
Crash due to lack of ACTION_OPEN_DOCUMENT

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#1281]
## Vespucci Version
git master 20201111, commit 1e62ca0e5e855cca8d5392a76656c8a67aab9fbe, built by me

## Android Version 
Pixel XL, Lineage 15.1  (Vespucci ran fine until just now)

## Behaviour/Symptoms
On startup, crash due to document permission missing.  I confirmed that vespucci has external storage permissions still.   I recently added a new geojson layer (a dozen points), and rebooted my phone (not about Vespucci).

```
    --------- beginning of crash
2020-11-11 15:59:42.909 13426-13426/de.blau.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.blau.android, PID: 13426
    java.lang.RuntimeException: Unable to start activity ComponentInfo{de.blau.android/de.blau.android.Main}: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{d18ac96 13426:de.blau.android/u0a169} (pid=13426, uid=10169) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{d18ac96 13426:de.blau.android/u0a169} (pid=13426, uid=10169) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.os.Parcel.readException(Parcel.java:2005)
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4758)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:5836)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2526)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1780)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1394)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1247)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:967)
        at de.blau.android.layer.geojson.MapOverlay.loadGeoJsonFile(MapOverlay.java:398)
        at de.blau.android.Map.setUpLayers(Map.java:252)
        at de.blau.android.Map.setPrefs(Map.java:989)
        at de.blau.android.Main.onStart(Main.java:681)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
        at android.app.Activity.performStart(Activity.java:7029)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
2020-11-11 15:59:42.909 13426-13426/de.blau.android I/ACRA: ACRA is disabled for de.blau.android - forwarding uncaught Exception on to default ExceptionHandler
```

## How to recreate
add geojson layers, reboot?

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
What Android version is running on the device?

**Comment by gdt** [comment]
8.1.0 via lineage

**Comment by gdt** [comment]
I commented out the loading of geojson layers in Map.java, and then it starts.  I have two layers. One is a bunch of lines, and the other is a few points.  Both rendered fine before the reboot.

**Comment by simonpoole** [comment]
This is a problem with from where you are loading the files. Android is only giving the app temporary permission to read the file, these are not persisted, by default, over reboot. Unluckily in my testing it doesn't seem possible to persist the permission in all cases, so we will have to live with this not always working as expected.

But in any case, the code now tries to persist the permission and if that doesn't work, it will show a toast, further the exception when opening the file is now caught and again a toast is displayed and the layer removed.

The alternative approach would be to copy the geojson file to the app specific storage, however that implies duplicating things and could potentially be very confusing for the user. Next year going forward we will have to decide how we want to handle all SAF related fall out as we will no longer be able to avoid it (you will not be able to load files except from the app specific directories in Android/data/....).

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/eab90120dcef21288b8857dd6b2e66847d413e9a

**Comment by gdt** [comment]
Wow, that's quite the mess!   I am loading files from /emulated/storage/0/Vespucci, which is where I have configured Vespucci to do everything, or was default.  That's where "export GPX" writes, and when I wanted geojson I just dropped them in there and did "add" from the layer menu.   I will update and see how that goes - thanks for looking at this so quickly.

**Comment by gdt** [comment]
For what it's worth, I had granted storage permission to Vespucci long ago, but I get it that this is some new-API-level SAF weirdness where even though there is general permission some calls use the restricted SAF model.

**Comment by gdt** [comment]
I moved my geojson files to /emulated/storage/0/Android/data/de.blau.android/files/layers and added them.  I got a toast about 'unable to persist permissions'.  When I restarted the layers were gone.   Easy to live with, re-adding them on reboot, now that there is no crash on start!

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/ab6a9ab6c54669c07f09654a1fc26f37afef8224 fixes the issue with the permissions not being persisted when it should be possible.

The main problem with SAF is that it severely limits where you can store things that you want kept even if the app is deinstalled (say a preset file or something like that), as the directories belonging to the app in Android/data/... will be removed on de-install.
