### ISSUE TITLE
NPE when retrieving WMS server capabilities

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1353]
> 03-07 12:09:25.888: E/AndroidRuntime(2546): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String de.blau.android.resources.TileLayerSource.getTileUrl()' on a null object reference
> 03-07 12:09:25.888: E/AndroidRuntime(2546): 	at de.blau.android.resources.WmsEndpointDatabaseView$EndpointAdapter$1.doInBackground(WmsEndpointDatabaseView.java:130)
> 03-07 12:09:25.888: E/AndroidRuntime(2546): 	at de.blau.android.resources.WmsEndpointDatabaseView$EndpointAdapter$1.doInBackground(WmsEndpointDatabaseView.java:122)
> 03-07 12:09:25.888: E/AndroidRuntime(2546): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
> 03-07 12:09:25.888: E/AndroidRuntime(2546): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/3017d63c4fae590fd6d32365ac870fe304acb3cd
