### ISSUE TITLE
NPE creating relation

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1403]
Submitted via crash dump

selected two ways and a point, then hit button to create relation, then for relation type selected "other"
--
`java.lang.NullPointerException:  Attempt to invoke virtual method  'de.blau.android.presets.PresetElementPath  de.blau.android.presets.Preset$PresetElement.a(de.blau.android.presets.Preset$PresetGroup)'  on a null object reference	
at j.a.a.v1.t0.a(ExtendSelectionActionModeCallback.java:76)	
at j.a.a.v1.q.a(Unknown Source:2)	at j.a.a.v1.s0.a(ElementSelectionActionModeCallback.java:218)	
at j.a.a.v1.m.onClick(Unknown Source:6)	at f.b.k.i.onItemClick(AlertController.java:1)	
at android.widget.AdapterView.performItemClick(AdapterView.java:376)

`

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/1e2f990c66b1e96a7522eb63cfe763944b71e9c4
