### ISSUE TITLE
NPE in RelationMembersFragment

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1404]
Submitted via crash dump
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean de.blau.android.osm.Way.r()' on a null object reference
at de.blau.android.propertyeditor.RelationMembersFragment.a(RelationMembersFragment.java:118)
at de.blau.android.propertyeditor.RelationMembersFragment.b(RelationMembersFragment.java:16)
at de.blau.android.propertyeditor.RelationMembersFragment.a(RelationMembersFragment.java:28)
at androidx.fragment.app.Fragment.b(Fragment.java:12)
```
Logcat
`

434 | 05-04 17:58:54.853 E/RelationMembersFragment( 3672): Element not downloaded for Rue Édouard Vaillant
-- | --
435 | 05-04 17:58:54.853 E/RelationMembersFragment( 3672): Element not downloaded for Rue Édouard Vaillant
436 | 05-04 17:58:54.853 E/RelationMembersFragment( 3672): Element not downloaded for Rue Édouard Vaillant
437 | 05-04 17:58:54.853 E/RelationMembersFragment( 3672): Element not downloaded for Rue Camille Desmoulins
438 | 05-04 17:58:54.853 E/RelationMembersFragment( 3672): Element not downloaded for Rue Camille Desmoulins
439 | 05-04 17:58:54.853 E/RelationMembersFragment( 3672): Element not downloaded for Rue Édouard Vaillant
440 | 05-04 17:58:54.853 E/RelationMembersFragment( 3672): Element not downloaded for Rue Roger Salengro

`

**Comment by simonpoole** [comment]
This might be caused by pruning, tentative fix don't rely on the downloaded flag in RelationMemberDescription instead always actually check if the element still exists.

Implemented in https://github.com/MarcusWolschon/osmeditor4android/commit/c50482fbab78f93bcda61da14a0b07cde2199e01
