### ISSUE TITLE
Editing screen while turn lane editing crashes Vespucci

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1726]
Description:
---

At least on my phone:

Open road for editing

Add `turn: lane` add tag

Add `left` and `right`

Rotate screen

Device info:
---
<table>
<tr><td>App version</td><td>18.0.0.1</td></tr>
<tr><td>App version code</td><td>2200</td></tr>
<tr><td>Android build version</td><td>V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.191002.002.V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Mateusz Konieczny"/>Mateusz Konieczny</A></td></tr>
</table>

**Comment by simonpoole** [comment]
@matkoniecz did you submit a crash dump? I tried to recreate here but didn't see the crash (but that might be due to me not running a quite identical version).

**Comment by matkoniecz** [comment]
I got this popup that error was reported (with word "purple" being used in description)

**Comment by matkoniecz** [comment]
Submitted again with description "turn lanes crash reproduced"

**Comment by mic140** [comment]
the same version of the program - the error is not reproduced

**Comment by simonpoole** [comment]
This looks like we are requesting focus too early or getUserVisibleHint() returning true when it shouldn't, which may be slightly Android OS / timing / whatever related. I suspect that the key difference is that @matkoniecz is on the _Details_ tab during rotation and @mic140 and myself are not.
```
Comment
purple swan - crashed randomly on rotating screen
De-obfuscated Stacktrace
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:908)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1577)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1424)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java:715)
	at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1316)
	at de.blau.android.propertyeditor.TagEditorFragment$1.onFocusChange(TagEditorFragment.java:1096)
	at android.view.View.onFocusChanged(View.java:7808)
	at android.widget.TextView.onFocusChanged(TextView.java:10789)
	at android.widget.AutoCompleteTextView.onFocusChanged(AutoCompleteTextView.java:1172)
	at android.view.View.handleFocusGainInternal(View.java:7478)
	at android.view.View.requestFocusNoSearch(View.java:12441)
	at android.view.View.requestFocus(View.java:12415)
	at android.view.View.requestFocus(View.java:12382)
	at android.view.View.requestFocus(View.java:12324)
	at de.blau.android.propertyeditor.TagEditorFragment.onCreateView(TagEditorFragment.java:329)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2722)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7825)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3295)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:57)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5239)
	at android.app.ActivityThread.access$3400(ActivityThread.java:220)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2027)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by matkoniecz** [comment]
It is not crashing for me in properties view, it is crashing in details view.

I can generate and submit bunch of crash reports if useful

**Comment by simonpoole** [comment]
> 
> I can generate and submit bunch of crash reports if useful

I don't think that is necessary, IMHO the relevant code should be in onStart in any case, if it is even really still needed (in the back of my head I think I remember it being necessary as a workaround at the time).

**Comment by simonpoole** [comment]
OK, I can recreate reliably now, however it requires pausing the app by leaving it, rotating, then returning to the app.
