### ISSUE TITLE
IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#420]
I noticed a **crash** which appears in the "Load Area" screen shown in this screenshot:

![vespucci-load-area](https://cloud.githubusercontent.com/assets/144518/13350083/19f8cf72-dc7e-11e5-83cd-8fa0b4233b71.png)

When the user executes the **search** the following error is logged to the console:

``` java
ACRA caught a IllegalStateException for de.blau.android
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1377)
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1395)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:616)
    at de.blau.android.dialogs.ProgressDialogFragment.dismissDialog(ProgressDialogFragment.java:57)
    at de.blau.android.dialogs.ProgressDialogFragment.showDialog(ProgressDialogFragment.java:38)
    at de.blau.android.util.Search$QueryNominatim.onPreExecute(Search.java:129)
    at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:591)
    at android.os.AsyncTask.execute(AsyncTask.java:539)
    at de.blau.android.util.Search.find(Search.java:101)
    at de.blau.android.BoxPicker$2.onEditorAction(BoxPicker.java:164)
    at android.widget.TextView.onEditorAction(TextView.java:4480)
    at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:139)
    at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:304)
    at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Thanks to _Git bisect_ I could easily track down the error to this commit:

* [Refactored all dialogs that don't contain a custom view or similar complications to use DialogFragment ...](https://github.com/MarcusWolschon/osmeditor4android/commit/4d5c8a18515b88955e032188be4fe7d9c1ce44bc)

Here is a blog post which explains the problem very well:

* [Fragment Transactions & Activity State Loss](http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html)

---

I might have time to look into the issue next week. If you want to work on it earlier feel free to do so.

**Comment by simonpoole** [comment]
This is typical google breakage (showing a progress dialog at the start of an AsyncTask and dismissing when finished is an extremely common pattern that should just work out of the box and not require workarounds).

The interesting question is why it happens in the BoxPicker activity and has not reared its ugly head in any of the other usages of progress dialogs in similar situations. Needs investigation.

The simple monkey patch is to currently not show the progress dialog and I'll have a look at how and if it can be fixed properly

**Comment by simonpoole** [comment]
There is one clear error in the code that I'm fixing as I write. Doesn't solve the more fundamental issue though.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/e045225574ba487e62e646f850dd5b4e30186749 fixes the specific cause of the crash, which was actually due to a C&P error on my behalf. As noted above the potential issue of this happening for real exists and needs to be addressed opening a separate issue for that.

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/issues/421
