### ISSUE TITLE
Handle disk/database full 

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#471]
Seems as if somebody managed to fill up their disk with tiles, causing the following exceptions:

> android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
> ###### 
> 
> Error Code : 13 (SQLITE_FULL)
> Caused By : No available space in disk.
> (database or disk is full (code 13))
> ###### 
> 
> at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
> at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:878)
> at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
> at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
> at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1637)
> at de.blau.android.services.util.OpenStreetMapTileProviderDataBase.deleteOldest(OpenStreetMapTileProviderDataBase.java:310)
> at de.blau.android.services.util.OpenStreetMapTileFilesystemProvider.saveFile(OpenStreetMapTileFilesystemProvider.java:107)
> at de.blau.android.services.util.OpenStreetMapTileDownloader$TileLoader.run(OpenStreetMapTileDownloader.java:124)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> at java.lang.Thread.run(Thread.java:818)

and 

> android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
> ###### 
> 
> Error Code : 13 (SQLITE_FULL)
> Caused By : No available space in disk.
> (database or disk is full (code 13))
> ###### 
> 
> at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
> at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:878)
> at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
> at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
> at de.blau.android.services.util.OpenStreetMapTileProviderDataBase.incrementUse(OpenStreetMapTileProviderDataBase.java:166)
> at de.blau.android.services.util.OpenStreetMapTileProviderDataBase.getTile(OpenStreetMapTileProviderDataBase.java:258)
> at de.blau.android.services.util.OpenStreetMapTileFilesystemProvider$TileLoader.run(OpenStreetMapTileFilesystemProvider.java:170)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> at java.lang.Thread.run(Thread.java:818)

while this doesn't crash the app, it creates 100s of crash dumps. Further there is currently no feedback to the user in question, nor a way for the user to resolve the issue.

**Comment by simonpoole** [comment]
Partially addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/a1ff67830e8afa652fe90e4bbe8124b9cf2855f5

**Comment by simonpoole** [comment]
And further fixes in https://github.com/MarcusWolschon/osmeditor4android/commit/98b0694edae09b4cbd9aa3109a4ee619412e5627
