### ISSUE TITLE
Test for max tag length enforcement fails on Android 6

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#593]
May be an Android issue, manually the issue can not be recreated, the issue does however cause the tests to completely abort.

java.lang.IndexOutOfBoundsException: setSpan (269 ... 269) ends beyond length 255 at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090) at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665) at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658) at android.text.Selection.setSelection(Selection.java:76) at android.text.Selection.setSelection(Selection.java:87) at android.widget.EditText.setSelection(EditText.java:98) at android.widget.EditText.performAccessibilityActionInternal(EditText.java:138) at android.view.View.performAccessibilityAction(View.java:8883) at android.view.AccessibilityInteractionController.performAccessibilityActionUiThread(AccessibilityInteractionController.java:668) at android.view.AccessibilityInteractionController.-wrap6(AccessibilityInteractionController.java) at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1194) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5417) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by simonpoole** [comment]
Disabled the test for 6.0 and earlier in https://github.com/MarcusWolschon/osmeditor4android/commit/b7b969362a372f2522ab3b9562a7a815fafb06db
