### ISSUE TITLE
Protect against OOM in gejson layer

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#995]
Some users are trying to load -very- large geojson files, which, naturally, fails.
```
java.lang.OutOfMemoryError: Failed to allocate a 603979784 byte allocation with 25165824 free bytes and 206MB until OOM, max allowed footprint 345110344, growth limit 536870912
at java.util.Arrays.copyOf(Arrays.java:3260)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:660)
at java.lang.StringBuilder.append(StringBuilder.java:203)
at de.blau.android.layer.geojson.MapOverlay.a(MapOverlay.java:497)
at de.blau.android.layer.geojson.MapOverlay.a(MapOverlay.java:475)
at de.blau.android.dialogs.Layers$1$1$1.a(Layers.java:165)
at de.blau.android.util.aj.a(SelectFile.java:178)
at de.blau.android.Main.onActivityResult(Main.java:2744)
```

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/e71f2102e9f5889c7326097b45bb1c5d35cbbe24
